# Generated by Django 2.2.3 on 2020-11-01 10:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('urls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='clicked',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='url',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='url',
            name='slug',
            field=models.SlugField(blank=True, max_length=30, unique=True),
        ),
    ]
